// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Specialist_Lab_2_2.Context;

#nullable disable

namespace Specialist_Lab_2_2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250804164414_CreateStartData")]
    partial class CreateStartData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Specialist_Lab_2_2.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Клиент - серверная разработка под .Net на языке C# ",
                            Duration = 40,
                            Title = "Net"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Программирование на Java. Уровень 2. Объектно - ориентированное программирование",
                            Duration = 20,
                            Title = "Java"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Язык программирования C#",
                            Duration = 40,
                            Title = "C#"
                        });
                });

            modelBuilder.Entity("Specialist_Lab_2_2.Models.CourseStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("CourseStudent");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 1,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 1,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 2,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 2,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 2,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 3,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 3,
                            StudentId = 8
                        },
                        new
                        {
                            Id = 9,
                            CourseId = 3,
                            StudentId = 9
                        });
                });

            modelBuilder.Entity("Specialist_Lab_2_2.Models.CourseTeacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("TeacherId");

                    b.ToTable("CourseTeacher");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 1,
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 2,
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 2,
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 3,
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 3,
                            TeacherId = 3
                        });
                });

            modelBuilder.Entity("Specialist_Lab_2_2.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Бондаренко Александр Вячеславович"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Иванов Иван Иванович"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Петров Петр Петрович"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Сергеев Сергей Сергеевич"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ибрагимов Ибрагим Ибрагимович"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Васильев Василий Васильевич"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Алексеев Алексей Алексеевич"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Викторов Виктор Викторович"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Ильин Илья Ильич"
                        });
                });

            modelBuilder.Entity("Specialist_Lab_2_2.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Шуйков Сергей Юрьевич"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Кораблин Александр Игоревич"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Герасименко Сергей Валерьевич"
                        });
                });

            modelBuilder.Entity("Specialist_Lab_2_2.Models.CourseStudent", b =>
                {
                    b.HasOne("Specialist_Lab_2_2.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Specialist_Lab_2_2.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Specialist_Lab_2_2.Models.CourseTeacher", b =>
                {
                    b.HasOne("Specialist_Lab_2_2.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Specialist_Lab_2_2.Models.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
